import type { Program, Interest } from "./types";

/**
 * Real Delaware programs (Newark / Bear / Middletown), compiled from provider
 * websites and flyers. Costs marked "estimate" in notes where the provider does
 * not publish a public weekly rate.
 */
export const PROGRAMS: Program[] = [
  {
    id: "de01",
    name: "Camp Cassey",
    organization: "Bear-Glasgow Family YMCA",
    type: "Day Camp",
    schedule: "Full Day",
    city: "Newark", state: "DE", zip: "19702",
    distanceMi: 3.1,
    ageMin: 5, ageMax: 14,
    costPerWeek: 320, weeks: 11,
    interests: ["Nature", "Swimming", "Sports", "Art", "Science"],
    description:
      "Primarily outdoor ACA-accredited day camp at 351 George Williams Way with daily swimming, weekly themes and field trips. Campers rotate through literacy, science, art, music & drama, team building and nature.",
    highlights: ["ACA accredited", "Daily swimming", "Weekly field trips", "Purchase of Care accepted"],
    uniqueness: 55, fun: 92, collegeImpact: 45,
    image: "https://images.unsplash.com/photo-1597149961419-cdcdfe9d1c43?w=800&q=80",
    startDate: "2026-06-08", endDate: "2026-08-24",
  },
  {
    id: "de02",
    name: "Camp Silver Lake",
    organization: "YMCA of Delaware",
    type: "Day Camp",
    schedule: "Full Day",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 14.6,
    ageMin: 5, ageMax: 13,
    costPerWeek: 320, weeks: 10,
    interests: ["Nature", "Sports", "Art", "Swimming"],
    description:
      "Traditional day camp at Silver Lake Elementary, 200 E. Cochran St. Completed K–7th graders rotate through arts and crafts, environmental education, team building, outdoor games and swimming.",
    highlights: ["Weekly adventures", "Youth sports options", "Financial assistance available"],
    uniqueness: 50, fun: 90, collegeImpact: 42,
    image: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&q=80",
    startDate: "2026-06-08", endDate: "2026-08-21",
  },
  {
    id: "de03",
    name: "Heron Day Camp",
    organization: "St. Anne's Episcopal School",
    type: "Day Camp",
    schedule: "Full Day",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 15.2,
    ageMin: 3, ageMax: 13,
    costPerWeek: 375, weeks: 8,
    interests: ["Art", "Science", "Sports", "Nature"],
    description:
      "Week-by-week traditional and specialty camps on the St. Anne's campus for preschool through middle school, with half-day and full-day options.",
    highlights: ["Half or full day", "Traditional + specialty tracks", "Register by the week"],
    uniqueness: 62, fun: 85, collegeImpact: 55,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    startDate: "2026-06-15", endDate: "2026-08-07",
  },
  {
    id: "de04",
    name: "ASPIRA Summer Camp",
    organization: "ASPIRA Academy of Delaware",
    type: "Day Camp",
    schedule: "Full Day",
    city: "Newark", state: "DE", zip: "19711",
    distanceMi: 5.4,
    ageMin: 5, ageMax: 13,
    costPerWeek: 235, weeks: 10,
    interests: ["Languages", "Art", "Sports", "Science"],
    description:
      "Themed weekly camp at 326 Ruthar Drive, 9:00am–4:00pm with before and after care by request. Breakfast and lunch daily, weekly field trips and splash days.",
    highlights: ["Meals included", "Extended care available", "Splash days", "Purchase of Care accepted"],
    uniqueness: 48, fun: 86, collegeImpact: 48,
    image: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&q=80",
    startDate: "2026-06-08", endDate: "2026-08-14",
  },
  {
    id: "de05",
    name: "Kids on Campus STEM Camps",
    organization: "Delaware Technical Community College",
    type: "STEM",
    schedule: "Half Day",
    city: "Newark", state: "DE", zip: "19713",
    distanceMi: 6.8,
    ageMin: 8, ageMax: 15,
    costPerWeek: 165, weeks: 1,
    interests: ["Coding", "Robotics", "Engineering", "Science"],
    description:
      "College-campus summer camps at the Stanton-Christiana Road campus covering coding, robotics, engineering, health sciences and more. One-week sessions, register per camp.",
    highlights: ["College campus", "Hands-on labs", "Many one-week sessions"],
    uniqueness: 72, fun: 78, collegeImpact: 84,
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80",
    startDate: "2026-06-22", endDate: "2026-08-14",
  },
  {
    id: "de06",
    name: "4-H Environmental Camp",
    organization: "University of Delaware Cooperative Extension",
    type: "Overnight",
    schedule: "Multi-Week",
    city: "Newark", state: "DE", zip: "19716",
    distanceMi: 7.5,
    ageMin: 9, ageMax: 14,
    costPerWeek: 250, weeks: 1,
    interests: ["Nature", "Science"],
    description:
      "Residential overnight camp exploring soil and environmental science through hands-on discovery — creek study, water quality and critter hunts with 4-H educators.",
    highlights: ["Overnight residential", "Hands-on science", "Statewide 4-H program"],
    uniqueness: 85, fun: 88, collegeImpact: 74,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    startDate: "2026-06-05", endDate: "2026-06-07",
  },
  {
    id: "de07",
    name: "Newark Parks & Recreation Summer Camps",
    organization: "City of Newark",
    type: "Day Camp",
    schedule: "Full Day",
    city: "Newark", state: "DE", zip: "19711",
    distanceMi: 4.0,
    ageMin: 5, ageMax: 12,
    costPerWeek: 180, weeks: 9,
    interests: ["Sports", "Art", "Nature"],
    description:
      "City-run neighborhood day camps and specialty recreation camps across Newark parks, registered week by week through the Parks & Recreation catalog.",
    highlights: ["City resident rates", "Neighborhood locations", "Weekly registration"],
    uniqueness: 40, fun: 84, collegeImpact: 35,
    image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&q=80",
    startDate: "2026-06-15", endDate: "2026-08-21",
  },
  {
    id: "de08",
    name: "Best Brains Full Day Summer Camp",
    organization: "Best Brains Middletown",
    type: "Academic",
    schedule: "Full Day",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 15.0,
    ageMin: 6, ageMax: 13,
    costPerWeek: 295, weeks: 8,
    interests: ["Chess", "Coding", "Writing", "Engineering", "Theater"],
    description:
      "Full-day themed academic camp, 8:30am–5:30pm. Weekly themes include Public Speaking & Play, Chess & Play, Engineering & Theater Workshop and Creative Coding.",
    highlights: ["8:30am–5:30pm coverage", "New academic theme weekly", "Small class sizes"],
    uniqueness: 66, fun: 74, collegeImpact: 80,
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80",
    startDate: "2026-06-15", endDate: "2026-08-07",
  },
  {
    id: "de09",
    name: "Martial Arts & Karate Summer Camp",
    organization: "Premier Martial Arts Bear",
    type: "Sports",
    schedule: "Full Day",
    city: "Bear", state: "DE", zip: "19701",
    distanceMi: 8.9,
    ageMin: 5, ageMax: 13,
    costPerWeek: 275, weeks: 8,
    interests: ["Martial Arts", "Sports", "Leadership"],
    description:
      "Structured indoor camp at 44 Fox Hunt Dr built around real martial arts training, weekly themes, confidence building and character development.",
    highlights: ["Daily martial arts training", "Indoor, all-weather", "Belt progression"],
    uniqueness: 70, fun: 88, collegeImpact: 45,
    image: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&q=80",
    startDate: "2026-06-15", endDate: "2026-08-14",
  },
  {
    id: "de10",
    name: "Spark Summer Camp",
    organization: "Middletown Summer Camp",
    type: "Day Camp",
    schedule: "Full Day",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 15.4,
    ageMin: 5, ageMax: 13,
    costPerWeek: 310, weeks: 10,
    interests: ["Martial Arts", "Sports", "Leadership", "Art"],
    description:
      "Grew out of a Middletown karate school in 2011 and expanded in 2020 into a full multi-activity camp focused on structure, confidence and character, not just supervision.",
    highlights: ["Coaching-led structure", "Character development focus", "Weekly themes"],
    uniqueness: 68, fun: 89, collegeImpact: 48,
    image: "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?w=800&q=80",
    startDate: "2026-06-15", endDate: "2026-08-21",
  },
  {
    id: "de11",
    name: "Love of Christ Summer Camp",
    organization: "Love of Christ Church",
    type: "Day Camp",
    schedule: "Weekly",
    city: "Bear", state: "DE", zip: "19701",
    distanceMi: 9.3,
    ageMin: 6, ageMax: 14,
    costPerWeek: 289, weeks: 1,
    interests: ["Sports", "Music", "Art"],
    description:
      "One-week co-ed camp at 2157 Bear Corbitt Road. Campers are grouped by the grade they completed in May.",
    highlights: ["Co-ed", "Single-week commitment", "Community-run"],
    uniqueness: 42, fun: 82, collegeImpact: 30,
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&q=80",
    startDate: "2026-07-27", endDate: "2026-07-31",
  },
  {
    id: "de12",
    name: "Enrichment STEAM Program",
    organization: "Wize Computing Academy at Whitehall Recreation Center",
    type: "STEM",
    schedule: "Weekly",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 15.8,
    ageMin: 7, ageMax: 14,
    costPerWeek: 30, weeks: 26,
    interests: ["Coding", "Robotics", "Engineering"],
    description:
      "26-week Saturday STEAM program (10–11am) at Whitehall Recreation Center, 735 Mapleton Ave., Suite 202, run by Wize Computing Academy with New Castle County Parks & Recreation. $780 total for the 26 weeks; monthly payment plan available, $35 non-refundable registration fee.",
    highlights: ["26-week program", "Saturdays 10–11am", "Monthly payment plan", "Early bird discount"],
    uniqueness: 80, fun: 82, collegeImpact: 86,
    image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800&q=80",
    startDate: "2026-10-17", endDate: "2027-04-24",
  },
  {
    id: "de13",
    name: "Bharatanatyam Classes & Free Trial",
    organization: "Navarasa School of Dance",
    type: "Arts",
    schedule: "Weekly",
    city: "Newark", state: "DE", zip: "19711",
    distanceMi: 4.7,
    ageMin: 5, ageMax: 18,
    costPerWeek: 35, weeks: 40,
    interests: ["Dance", "Music", "Theater"],
    description:
      "Classical Bharatanatyam instruction with Rachana Raghu near People's Plaza, Newark. Free trial class offered; kids and adults welcome, all experience levels.",
    highlights: ["Free trial class", "Classical Indian dance", "Kids & adults", "Year-round"],
    uniqueness: 90, fun: 84, collegeImpact: 70,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
    startDate: "2026-09-04", endDate: "2027-06-11",
  },
  {
    id: "de14",
    name: "Summer Art Camp — July Schedule",
    organization: "Middletown Community Art Camp",
    type: "Arts",
    schedule: "Half Day",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 15.1,
    ageMin: 5, ageMax: 15,
    costPerWeek: 100, weeks: 1,
    interests: ["Art"],
    description:
      "Five days, five different arts and crafts, 11:00am–1:00pm in Middletown. Painting, fun crafts, mixed media and creative art techniques, with a take-home masterpiece every day. Beginner friendly. Two July weeks offered: July 6–10 and July 20–24.",
    highlights: ["$100 per week", "Take-home art daily", "Beginner friendly", "Enroll by June 30"],
    uniqueness: 64, fun: 90, collegeImpact: 40,
    image: "https://images.unsplash.com/photo-1499892477393-f675706cbe6e?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-10",
  },
  {
    id: "de15",
    name: "Kids' Paint Parties & Art Workshops",
    organization: "Shilpi Fine Arts",
    type: "Specialty",
    schedule: "Half Day",
    city: "Middletown", state: "DE", zip: "19709",
    distanceMi: 14.9,
    ageMin: 5, ageMax: 17,
    costPerWeek: 45, weeks: 1,
    interests: ["Art"],
    description:
      "Guided painting sessions with artist Shilpi — kids' birthday paint parties, group workshops and Indian folk art sessions. Live painting demonstrations at community events.",
    highlights: ["Birthday paint parties", "Indian folk art", "All supplies provided"],
    uniqueness: 88, fun: 86, collegeImpact: 38,
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
    startDate: "2026-06-15", endDate: "2026-08-28",
  },
];

export const ALL_INTERESTS: Interest[] = [
  "Coding", "Robotics", "Music", "Dance", "Theater", "Art", "Sports",
  "Martial Arts", "Swimming", "Nature", "Science", "Writing", "Leadership",
  "Cooking", "Languages", "Math", "Chess", "Engineering", "Filmmaking",
];

export const ALL_TYPES = [
  "Day Camp", "Overnight", "Academic", "Sports", "Arts", "STEM", "Outdoor", "Specialty",
] as const;

export const ALL_SCHEDULES = ["Half Day", "Full Day", "Weekly", "Multi-Week"] as const;
