import type { Program, Interest } from "./types";

const cities = [
  ["Brooklyn", "NY", "11201"],
  ["Cambridge", "MA", "02139"],
  ["Austin", "TX", "78701"],
  ["Boulder", "CO", "80301"],
  ["Portland", "OR", "97205"],
  ["Asheville", "NC", "28801"],
  ["Berkeley", "CA", "94704"],
  ["Evanston", "IL", "60201"],
  ["Bethesda", "MD", "20814"],
  ["Santa Monica", "CA", "90401"],
] as const;

const c = (i: number) => cities[i % cities.length];

export const PROGRAMS: Program[] = [
  {
    id: "p01", name: "Wildwood Coding Quest", organization: "Hackbright Kids",
    type: "STEM", schedule: "Weekly", ...loc(0), distanceMi: 4.2,
    ageMin: 8, ageMax: 13, costPerWeek: 525, weeks: 2,
    interests: ["Coding", "Robotics", "Math"],
    description: "Build games in Scratch and Python while exploring a forest campus. Each week ends with a parents-night arcade demo.",
    highlights: ["Outdoor coding lab", "1:6 ratio", "Showcase event"],
    uniqueness: 86, fun: 88, collegeImpact: 78,
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80",
    startDate: "2026-06-22", endDate: "2026-07-03",
  },
  {
    id: "p02", name: "Lakeshore Sailing Academy", organization: "Blue Wave",
    type: "Outdoor", schedule: "Full Day", ...loc(4), distanceMi: 12.8,
    ageMin: 10, ageMax: 17, costPerWeek: 690, weeks: 1,
    interests: ["Nature", "Sports", "Leadership"],
    description: "Learn to skipper a Sunfish, read wind, and lead a crew. Capstone regatta on Friday.",
    highlights: ["US Sailing certified", "Capstone regatta", "Small crews"],
    uniqueness: 78, fun: 92, collegeImpact: 65,
    image: "https://images.unsplash.com/photo-1500627964684-141351970a7f?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-10",
  },
  {
    id: "p03", name: "Studio One Filmmakers", organization: "Reel Kids",
    type: "Arts", schedule: "Multi-Week", ...loc(2), distanceMi: 6.1,
    ageMin: 12, ageMax: 18, costPerWeek: 740, weeks: 3,
    interests: ["Filmmaking", "Writing", "Art"],
    description: "Write, shoot, and edit a short film with mentors from the local film festival. Premieres at indie cinema.",
    highlights: ["Festival premiere", "Industry mentors", "Professional gear"],
    uniqueness: 91, fun: 84, collegeImpact: 88,
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80",
    startDate: "2026-07-13", endDate: "2026-07-31",
  },
  {
    id: "p04", name: "Junior Chef Bootcamp", organization: "Sapore",
    type: "Specialty", schedule: "Half Day", ...loc(1), distanceMi: 3.4,
    ageMin: 7, ageMax: 12, costPerWeek: 380, weeks: 1,
    interests: ["Cooking"],
    description: "Knife skills, baking, and a pop-up dinner cooked for parents on Friday.",
    highlights: ["Pop-up dinner", "Take-home recipes", "Allergy-aware"],
    uniqueness: 70, fun: 90, collegeImpact: 38,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-10",
  },
  {
    id: "p05", name: "Mountain Trail Adventure", organization: "Summit Y",
    type: "Overnight", schedule: "Multi-Week", ...loc(3), distanceMi: 38.0,
    ageMin: 11, ageMax: 16, costPerWeek: 920, weeks: 2,
    interests: ["Nature", "Sports", "Leadership"],
    description: "Two weeks of backpacking, climbing, and bouldering. Optional 4-day backcountry trek.",
    highlights: ["Backcountry trek", "Climbing wall", "Leave-no-trace"],
    uniqueness: 82, fun: 95, collegeImpact: 72,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    startDate: "2026-07-20", endDate: "2026-07-31",
  },
  {
    id: "p06", name: "MIT-Style Math Circle", organization: "Proof School",
    type: "Academic", schedule: "Half Day", ...loc(1), distanceMi: 2.0,
    ageMin: 13, ageMax: 17, costPerWeek: 595, weeks: 3,
    interests: ["Math", "Science"],
    description: "Olympiad-level problem solving with college math majors. Weekly mock contests.",
    highlights: ["AMC prep", "Mock contests", "College mentors"],
    uniqueness: 74, fun: 70, collegeImpact: 96,
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-24",
  },
  {
    id: "p07", name: "Stage Lights Musical Theater", organization: "Curtain Call",
    type: "Arts", schedule: "Full Day", ...loc(7), distanceMi: 9.7,
    ageMin: 9, ageMax: 15, costPerWeek: 560, weeks: 2,
    interests: ["Theater", "Music"],
    description: "Cast, rehearse, and perform a full Broadway Jr. musical in two weeks.",
    highlights: ["Full production", "Pro choreographer", "Two performances"],
    uniqueness: 65, fun: 93, collegeImpact: 60,
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&q=80",
    startDate: "2026-07-13", endDate: "2026-07-24",
  },
  {
    id: "p08", name: "Robotics League", organization: "FIRST Local",
    type: "STEM", schedule: "Weekly", ...loc(8), distanceMi: 5.5,
    ageMin: 10, ageMax: 16, costPerWeek: 645, weeks: 2,
    interests: ["Robotics", "Engineering", "Coding"],
    description: "Design, build, and battle VEX bots. Travel to a friendly weekend tournament.",
    highlights: ["VEX competition", "CAD instruction", "Tournament travel"],
    uniqueness: 79, fun: 86, collegeImpact: 90,
    image: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-17",
  },
  {
    id: "p09", name: "Tide Pool Marine Biology", organization: "Ocean Lab",
    type: "Academic", schedule: "Full Day", ...loc(9), distanceMi: 14.2,
    ageMin: 11, ageMax: 17, costPerWeek: 710, weeks: 1,
    interests: ["Science", "Nature"],
    description: "Daily field work with marine biologists on the Pacific. Tag fish, ID kelp, present findings.",
    highlights: ["Daily fieldwork", "Working scientists", "Research project"],
    uniqueness: 88, fun: 80, collegeImpact: 92,
    image: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=800&q=80",
    startDate: "2026-07-20", endDate: "2026-07-24",
  },
  {
    id: "p10", name: "All-Star Soccer Academy", organization: "GoalCraft",
    type: "Sports", schedule: "Full Day", ...loc(2), distanceMi: 3.9,
    ageMin: 6, ageMax: 14, costPerWeek: 425, weeks: 1,
    interests: ["Sports"],
    description: "Position-specific drills, tactical sessions, and Friday tournament. UEFA-licensed coaches.",
    highlights: ["UEFA coaches", "Friday tournament", "Video review"],
    uniqueness: 45, fun: 88, collegeImpact: 55,
    image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&q=80",
    startDate: "2026-06-29", endDate: "2026-07-03",
  },
  {
    id: "p11", name: "Painters & Printmakers Studio", organization: "Inkwell",
    type: "Arts", schedule: "Half Day", ...loc(5), distanceMi: 7.6,
    ageMin: 8, ageMax: 14, costPerWeek: 410, weeks: 2,
    interests: ["Art"],
    description: "Acrylic, watercolor, and screen printing. Build a personal portfolio.",
    highlights: ["Portfolio building", "Gallery night", "Free supplies"],
    uniqueness: 60, fun: 78, collegeImpact: 58,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-17",
  },
  {
    id: "p12", name: "Young Writers Workshop", organization: "Inkpot",
    type: "Academic", schedule: "Half Day", ...loc(0), distanceMi: 1.4,
    ageMin: 11, ageMax: 17, costPerWeek: 475, weeks: 2,
    interests: ["Writing"],
    description: "Fiction, poetry and creative nonfiction with published authors. Submit to a teen literary magazine.",
    highlights: ["Published authors", "Submit your work", "Small workshop"],
    uniqueness: 72, fun: 68, collegeImpact: 86,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    startDate: "2026-07-13", endDate: "2026-07-24",
  },
  {
    id: "p13", name: "Global Languages Immersion", organization: "Polyglot Camp",
    type: "Specialty", schedule: "Full Day", ...loc(6), distanceMi: 10.8,
    ageMin: 10, ageMax: 16, costPerWeek: 580, weeks: 2,
    interests: ["Languages"],
    description: "Choose Spanish, Mandarin, or French. English-free zone with native speakers.",
    highlights: ["Native speakers", "English-free zone", "Cultural cooking"],
    uniqueness: 75, fun: 74, collegeImpact: 82,
    image: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-17",
  },
  {
    id: "p14", name: "Skate & BMX Park", organization: "Wheelhouse",
    type: "Sports", schedule: "Half Day", ...loc(4), distanceMi: 5.0,
    ageMin: 8, ageMax: 16, costPerWeek: 360, weeks: 1,
    interests: ["Sports"],
    description: "Beginner to vert ramps. Helmet & pads provided.",
    highlights: ["Pro instruction", "Gear included", "Friday jam"],
    uniqueness: 68, fun: 94, collegeImpact: 35,
    image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
    startDate: "2026-08-03", endDate: "2026-08-07",
  },
  {
    id: "p15", name: "Astronaut Academy", organization: "Space Forge",
    type: "STEM", schedule: "Full Day", ...loc(8), distanceMi: 18.3,
    ageMin: 11, ageMax: 17, costPerWeek: 850, weeks: 1,
    interests: ["Science", "Engineering"],
    description: "Mission simulator, rocket build, and a high-altitude balloon launch.",
    highlights: ["Mission sim", "Rocket launch", "NASA mentor visit"],
    uniqueness: 95, fun: 89, collegeImpact: 91,
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
    startDate: "2026-07-27", endDate: "2026-07-31",
  },
  {
    id: "p16", name: "Tiny Naturalists", organization: "Acorn Trail",
    type: "Day Camp", schedule: "Full Day", ...loc(5), distanceMi: 4.6,
    ageMin: 5, ageMax: 8, costPerWeek: 340, weeks: 1,
    interests: ["Nature", "Science"],
    description: "Bug-hunting, creek splashing, and forest forts. Pure summer joy.",
    highlights: ["Forest forts", "Creek time", "Daily nature journal"],
    uniqueness: 55, fun: 96, collegeImpact: 30,
    image: "https://images.unsplash.com/photo-1597149961419-cdcdfe9d1c43?w=800&q=80",
    startDate: "2026-06-29", endDate: "2026-07-03",
  },
  {
    id: "p17", name: "Debate & Model UN Institute", organization: "Forum",
    type: "Academic", schedule: "Full Day", ...loc(8), distanceMi: 7.2,
    ageMin: 13, ageMax: 18, costPerWeek: 695, weeks: 2,
    interests: ["Leadership", "Writing"],
    description: "Cross-ex, Lincoln-Douglas, and Model UN with Ivy coaches. End-of-camp tournament.",
    highlights: ["Ivy coaches", "Mock tournament", "Public speaking"],
    uniqueness: 70, fun: 66, collegeImpact: 94,
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80",
    startDate: "2026-07-13", endDate: "2026-07-24",
  },
  {
    id: "p18", name: "Circus Arts & Acrobatics", organization: "BigTop Kids",
    type: "Specialty", schedule: "Weekly", ...loc(7), distanceMi: 6.4,
    ageMin: 7, ageMax: 14, costPerWeek: 495, weeks: 2,
    interests: ["Theater", "Art"],
    description: "Aerial silks, juggling, unicycle. Circus showcase under a real big top.",
    highlights: ["Aerial silks", "Big top show", "Wear a costume"],
    uniqueness: 92, fun: 95, collegeImpact: 50,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    startDate: "2026-07-13", endDate: "2026-07-24",
  },
  {
    id: "p19", name: "Junior Vet Lab", organization: "PawScience",
    type: "Specialty", schedule: "Half Day", ...loc(3), distanceMi: 8.2,
    ageMin: 9, ageMax: 14, costPerWeek: 455, weeks: 1,
    interests: ["Science", "Nature"],
    description: "Shadow vets, learn anatomy, meet shelter animals. Empathy meets science.",
    highlights: ["Vet shadowing", "Live animals", "Anatomy lab"],
    uniqueness: 84, fun: 87, collegeImpact: 76,
    image: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800&q=80",
    startDate: "2026-08-03", endDate: "2026-08-07",
  },
  {
    id: "p20", name: "Esports & Game Design", organization: "Arena Camp",
    type: "STEM", schedule: "Full Day", ...loc(6), distanceMi: 11.0,
    ageMin: 10, ageMax: 17, costPerWeek: 530, weeks: 2,
    interests: ["Coding", "Filmmaking"],
    description: "Build a 2D game in Unity, learn streaming, and compete in a friendly tournament.",
    highlights: ["Unity build", "Streaming setup", "Tournament"],
    uniqueness: 73, fun: 92, collegeImpact: 64,
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    startDate: "2026-07-20", endDate: "2026-07-31",
  },
  {
    id: "p21", name: "Songwriters Sessions", organization: "Loop Studio",
    type: "Arts", schedule: "Half Day", ...loc(2), distanceMi: 4.8,
    ageMin: 11, ageMax: 17, costPerWeek: 510, weeks: 2,
    interests: ["Music", "Writing"],
    description: "Write, record, and release an original song to streaming platforms.",
    highlights: ["Record an original", "Release on Spotify", "Pro studio"],
    uniqueness: 87, fun: 85, collegeImpact: 70,
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80",
    startDate: "2026-07-13", endDate: "2026-07-24",
  },
  {
    id: "p22", name: "Equestrian Riding School", organization: "Bridle Path",
    type: "Sports", schedule: "Full Day", ...loc(3), distanceMi: 22.4,
    ageMin: 8, ageMax: 16, costPerWeek: 875, weeks: 1,
    interests: ["Sports", "Nature"],
    description: "English riding, horsemanship and stable care. Friday show.",
    highlights: ["Daily riding", "Friday show", "All levels"],
    uniqueness: 76, fun: 91, collegeImpact: 48,
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    startDate: "2026-07-06", endDate: "2026-07-10",
  },
  {
    id: "p23", name: "Entrepreneurship Lab", organization: "BuildIt Teen",
    type: "Academic", schedule: "Full Day", ...loc(0), distanceMi: 2.6,
    ageMin: 13, ageMax: 18, costPerWeek: 720, weeks: 2,
    interests: ["Leadership", "Math", "Writing"],
    description: "Pitch a startup, build an MVP, present to real investors on demo day.",
    highlights: ["Real investors", "Demo day", "MVP build"],
    uniqueness: 80, fun: 75, collegeImpact: 93,
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80",
    startDate: "2026-07-20", endDate: "2026-07-31",
  },
  {
    id: "p24", name: "Backyard Sports Sampler", organization: "PlayDay",
    type: "Day Camp", schedule: "Full Day", ...loc(4), distanceMi: 1.9,
    ageMin: 5, ageMax: 10, costPerWeek: 295, weeks: 1,
    interests: ["Sports"],
    description: "Soccer, kickball, capture the flag. Classic summer at a neighborhood park.",
    highlights: ["Walking distance", "All-weather", "Friend referral discount"],
    uniqueness: 30, fun: 88, collegeImpact: 25,
    image: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&q=80",
    startDate: "2026-06-22", endDate: "2026-06-26",
  },
];

function loc(i: number) {
  const [city, state, zip] = c(i);
  return { city, state, zip };
}

export const ALL_INTERESTS: Interest[] = [
  "Coding", "Robotics", "Music", "Theater", "Art", "Sports",
  "Nature", "Science", "Writing", "Leadership", "Cooking",
  "Languages", "Math", "Engineering", "Filmmaking",
];

export const ALL_TYPES = [
  "Day Camp", "Overnight", "Academic", "Sports", "Arts", "STEM", "Outdoor", "Specialty",
] as const;

export const ALL_SCHEDULES = ["Half Day", "Full Day", "Weekly", "Multi-Week"] as const;